### ISSUE TITLE
中奖值太过集中了

### ISSUE THREAD

**Issue by woaiso** [bigertech/lottery#1]
获奖的编号集中在1~10W（79个） 、10W以上（21个），两个区间 10W~100W 一个奖都木有

**Comment by shanelau** [comment]
恩，确实如此。但是 抽奖保证足够随机就行，不需要保证他的区间分布

10W中选79个的概率其实很小了，
第一个数的随机性也足够大了，所有总体来说还是随机的

如果奖品只有10个呢？  你觉得应该怎么分

当然算法还有很大的改进空间

比如 第一个数是 A
那第二个数就是   A + 1223
那第三个数就是   A + 1223 \* 1223
那第四个数就是   A + 1223 _1223_ 1223

**Comment by woaiso** [comment]
恩，随机性从逻辑出发确实没有任何问题。但是用户不关心这些，用户看到的结果就是奖品非常集中，中间空白实在太大。传达出了不公平的错误信号，确实有时候不能光认为逻辑正确就行了，更多的还是从用户角度思考啊。

**Comment by xndcn** [comment]
如果seed=totalPeople/count会不会好些？

**Comment by shanelau** [comment]
@xndcn 你说的太有道理了，机智
